spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root1234!

  jpa:
    hibernate:
      ddl-auto: create-drop
